language: node_js
node_js:
- '7'
script:
- echo "Test"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_e8ec75924147_key -iv $encrypted_e8ec75924147_iv
  -in github_deploy_key.enc -out github_deploy_key -d
