nguage: ruby
rvm:
    - 2.3.3
services:
    - postgresql
    - redis-server
before_install:
    - "echo '--colour' > ~/.rspec"
    - "echo 'gem: --no-document' > ~/.gemrc"
    - gem update --system
before_script:
    - psql -c "CREATE USER \"rails-template\" WITH PASSWORD 'rails-bootstrap';" -U postgres
    - psql -c "DROP DATABASE IF EXISTS \"rails-template_test\";" -U postgres
    - psql -c "CREATE DATABASE \"rails-template_test\" ENCODING 'utf8';" -U postgres
    - bundle exec rake db:migrate
script:
    - bundle exec rubocop app -R --format simple
