default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: octolive
  password: octolive

development:
  <<: *default
  database: octolive_development

test:
  <<: *default
  database: octolive_test

production:
  <<: *default
  database: octolive_production
  password: <%= ENV['RAILS-TEMPLATE_DATABASE_PASSWORD'] %>
