default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails-template
  password: rails-template

development:
  <<: *default
  database: rails-template_development
  
test:
  <<: *default
  database: rails-template_test

production:
  <<: *default
  database: rails-template_production
  password: <%= ENV['RAILS-TEMPLATE_DATABASE_PASSWORD'] %>
